# services-elascale-hpa-optimized.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cartservice-elascale-optimized
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cartservice
  minReplicas: 2  # As you specified
  maxReplicas: 15
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # Immediate response
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 180  # More conservative
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 45  # Your aggressive threshold
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
