---
# Frontend Service HPA - FIXED VERSION
# Formula: f = 0.5·CPU + 0.3·MEM + 0.2·REP (frontend-cart dependency)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-elascale
  namespace: default
  labels:
    optimization: elascale-fixed
    service: frontend
  annotations:
    description: "User-facing service - network and CPU intensive"
    formula: "f = 0.5·CPU + 0.3·MEM + 0.2·REP"
    changes: "Increased CPU threshold from 55% to 68%, reduced max scale-up from 4 to 3 pods"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 20
  
  metrics:
  # FIX: Increased CPU from 55% to 68% (closer to baseline 70%)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 68  # Was 55%, now 68%
  
  # Memory threshold appropriate for frontend
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  
  behavior:
    scaleUp:
      # FIX: Added small stabilization window to prevent thrashing
      stabilizationWindowSeconds: 15  # Was 20s, now 15s
      policies:
      # FIX: Reduced from +4 pods to +3 pods
      - type: Pods
        value: 3  # Was 4, now 3
        periodSeconds: 30
      - type: Percent
        value: 100  # Double capacity
        periodSeconds: 30
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min

---
# Checkout Service HPA - FIXED VERSION
# Formula: f = 0.6·CPU + 0.3·MEM + 0.1·REP
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checkoutservice-elascale
  namespace: default
  labels:
    optimization: elascale-fixed
    service: checkoutservice
  annotations:
    description: "CPU-intensive business logic"
    formula: "f = 0.6·CPU + 0.3·MEM + 0.1·REP"
    changes: "Increased CPU threshold from 60% to 70%, matches baseline"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice
  minReplicas: 2
  maxReplicas: 12
  
  metrics:
  # FIX: Increased CPU from 60% to 70% (match baseline)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Was 60%, now 70%
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  
  behavior:
    scaleUp:
      # FIX: Added stabilization to prevent overscaling
      stabilizationWindowSeconds: 30
      policies:
      # FIX: Reduced from +3 to +2 pods
      - type: Pods
        value: 2  # Was 3, now 2
        periodSeconds: 30
      - type: Percent
        value: 50
        periodSeconds: 30
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min

---
# Product Catalog Service HPA - FIXED VERSION
# Formula: f = 0.3·CPU + 0.5·MEM + 0.2·REP (memory-intensive caching)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogservice-elascale
  namespace: default
  labels:
    optimization: elascale-fixed
    service: productcatalogservice
  annotations:
    description: "Memory-intensive catalog caching"
    formula: "f = 0.3·CPU + 0.5·MEM + 0.2·REP"
    changes: "Increased CPU from 65% to 70%, lowered memory to 65%"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogservice
  minReplicas: 2
  maxReplicas: 10
  
  metrics:
  # FIX: Increased CPU threshold to 70%
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Was 65%, now 70%
  
  # Memory is more critical for catalog caching
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 65  # Was 70%, now 65%
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 45
      policies:
      - type: Pods
        value: 2
        periodSeconds: 45
      - type: Percent
        value: 50
        periodSeconds: 45
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 150
      - type: Percent
        value: 10
        periodSeconds: 150
      selectPolicy: Min

---
# Recommendation Service HPA - FIXED VERSION
# Formula: f = 0.7·CPU + 0.3·MEM (very CPU intensive ML)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendationservice-elascale
  namespace: default
  labels:
    optimization: elascale-fixed
    service: recommendationservice
  annotations:
    description: "ML/recommendation engine - very CPU intensive"
    formula: "f = 0.7·CPU + 0.3·MEM"
    changes: "Increased CPU from 65% to 70%, increased memory to 75%"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  minReplicas: 1
  maxReplicas: 8
  
  metrics:
  # FIX: Increased CPU to 70% (was causing thrashing at 65%)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Was 65%, now 70%
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  
  behavior:
    scaleUp:
      # FIX: Added stabilization to prevent oscillation
      stabilizationWindowSeconds: 45  # Was 30s, now 45s
      policies:
      - type: Pods
        value: 2
        periodSeconds: 45
      - type: Percent
        value: 100
        periodSeconds: 45
      selectPolicy: Max
    
    scaleDown:
      # FIX: Longer stabilization for ML workloads
      stabilizationWindowSeconds: 420  # 7 minutes (was 5 minutes)
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180
      - type: Percent
        value: 10
        periodSeconds: 180
      selectPolicy: Min
